### ISSUE TITLE
pypelib wrong exception parsing in Django driver

### ISSUE THREAD

**Issue by lbergesio** [fp7-ofelia/ocf#100]
File pypelib/persistence/backends/django/Django.py , Line 157
Can't concatenate string and exception ==> casting missing

**Comment by lbergesio** [comment]
Fixed line adding str(e):
raise Exception("[Django Driver] Some error occurred when trying to fetch table table with name: " + tableName + ". Exception: " + str(e)).

Left issue open to regenerate .deb

**Comment by CarolinaFernandez** [comment]
Updated source and .deb's in googlecode.

Also...
- RuleTableModel.name was reverted (to a non Unique field, since there were some [incompatibilities between TextField and the parameter "unique"](https://code.djangoproject.com/ticket/2495). See #99)
- Installation/upgrade logic (previously inside ofver) is now inside pypelib as a standalone library

And finally, as a reminder:

**Do not parse ls -l output, since its implementation varies between Ubuntu and Debian, and so on**

Ubuntu

> DIRS=`ls -l /usr/lib/ | grep "python2" | egrep '^d' | awk '{print $8}'`

Debian

> DIRS=`ls -l /usr/lib/ | grep "python2" | egrep '^d' | awk '{print $9}'`

**Use this instead :) [[detailed explanation here](http://stackoverflow.com/questions/1447809/awk-print-9-the-last-ls-l-column-including-any-spaces-in-the-file-name)]**

> DIRS=`find /usr/lib -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | grep "python2"`
