### ISSUE TITLE
Update ofver repository with lock() changes

### ISSUE THREAD

**Issue by lbergesio** [fp7-ofelia/ocf#102]
Update ofver repository in google code with the changes performed in the lock() function as it is in v0.4 of OCF.

Consider rolling back to a better implemented lock system based on lock file.

**Comment by CarolinaFernandez** [comment]
I personally think it is better to have a non-file dependent system rather than the classic one that uses files; as long as it does not keep on failing. We'll be seeing this.

If it were to fail again under some environments and then if it was chosen to rollback, [keyboard interruptions](http://kb.mit.edu/confluence/pages/viewpage.action?pageId=3907156) should be implemented to avoid old .lock files blocking execution of a new instance in the future.

For any other script this is interesting too.

**Comment by lbergesio** [comment]
At least one of the problems of this mechanism is that if some other application out of vt am, expedient, optin, agent are using ofver at the same time they will be locked

**Comment by CarolinaFernandez** [comment]
I guess there may be some more drawbacks with this new locking system, but I don't think that this it is blocking to other instances of ofver in different folders. If two **ofver.sh** (*) files with the lock method are executed in different folders there's not any problem with it... As it happens if they are run in the same folder. At least in my computer, but I cannot assure this work okay everywhere, of course.

The following line supposedly controls that any instance running under the same folder blocks a new one; but it does not / should not affect any other:

> `pwdx ${pids[$i]} | awk '{print $2}'` == $PWD

This could be improved, sure. Right now the "runningInstances" are filtered by the name (ofver) and one of the commands {install, upgrade}; but we could remove this last filter to be more general.

And of course we can consider reverting back to the old system if it were to be better (improving at least the treatment of these .lock files).

(*) File for testing...

> ```
> #!/bin/bash
> function lock()
> {
>         currentPID=$$
>         runningInstances=`ps aux | grep "ofver" | grep -v "grep" | awk '{print $2}'`
>         pids=($runningInstances)
>         numProcesses=`echo ${#pids[@]}`
>         for (( i = 0; i < $numProcesses; i++ )); do
>                 # Do not lock if older PIDs running and these run in the same folder
>                 if [[ $((pids[$i]+0)) -lt $((currentPID-1)) &&
>                 `pwdx ${pids[$i]} | awk '{print $2}'` == $PWD ]]; then
>                         echo "FATAL ERROR: Could not acquire lock... Other instance (PID ${pids[$i]}) of ofver is already running."
>                         exit 1
>                 fi
>         done
> }
> lock
> echo "Only running once at a time"
> sleep 30
> ```

**Comment by CarolinaFernandez** [comment]
Done, uploaded to OCF and to googlecode.

**Important note**: ofver _respawns_ inside itself, therefore having conflicts with the previous code versions (since it avoids executing any new instance under the same directory when previous instances are still running).

In order to solve this, a **parent process control** has been implemented: ofver instance can run with previous ofver instances under the same directory **iff** these previous instances are parent processes to the new ones.

New code is as follows:

> ```
> #Aux functions for lock
> function is_number()
> {
>     printf '%f' "$1" &>/dev/null && echo "1" || echo "0";
> }
> 
> function get_parent_pid()
> {
>     process=$1
>     while [[ `is_number $process` == 1 ]]; do
>         if [[ $process -gt 0 ]]; then
>             process=`cat /proc/$((process))/stat | awk '{print $4 }'`
>             echo $process
>         else
>             break
>         fi
>     done
> }
> 
> function contains_element()
> {
>         local e
>         for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 1; done
>         return 0
> }
> 
> #Check that no other OFVER instance is already running
> function lock()
> {
>         currentPID=$$
>         pids=( $(ps aux | grep "ofver" | grep "bash" | grep -v "grep" | awk '{print $2}') )
>         for pid in "${pids[@]}"; do
>                 # Do not lock if non-related (not parent of the current
>                 # process) and older PIDs run in the same folder
>                 if [[ $pid -lt $((currentPID-1)) &&
>                 `pwdx $pid | awk '{print $2}'` == $PWD ]]; then
>                         pidFromParent=0
>                         if [[ $ENABLE_OFVER_SON_PROCESSES -eq 1 ]]; then
>                                 parent_pids=( $(get_parent_pid $currentPID) )
>                                contains_element $pid "${parent_pids[@]}"
>                                 pidFromParent=$?
>                         fi
>                         if [[ $pidFromParent -eq 0 ]]; then
>                                 print "${txtred}FATAL ERROR:${txtrst} Could not acquire lock... Other instance (PID $pid) of ofver is already running."
>                                 exit 1
>                         fi
>                 fi
>         done
> }
> ```
