### ISSUE TITLE
Differentiate exceptions when creating VMs

### ISSUE THREAD

**Issue by CarolinaFernandez** [fp7-ofelia/ocf#119]
The creation of a VM may fail due to many reasons:
- Some error in XEN
- There is a VM with the same name in the same slice and project
- ...

Related to the 2nd point: this is checked at Expedient (VM name is checked against the list in the database); **but when the VM is created from the outside** and there was **already another VM** with the same name in the very same project and slice; an exception is raised and the configuration files in both "remote" (stopped) and "cache" (running) folders are deleted.

It is necessary to handle exceptions in a different way when these happen because of a duplicate VM (duplicate name) or because of any other error.

**Comment by msune** [comment]
An easy alternative, but which needs a backwards compatibility (this is easily done), is to create .conf files like:

``` python
name_VMUUID.conf
```

For new VMs; when an old VM is started (pseudo-code):

``` python
try:
   //Open name_VMUUID.conf
catch:
    try:
        //Open name.conf => backwards compatibility:
    catch:
        //Raise exception
```

**Comment by lbergesio** [comment]
This is not a good solution, because new VMs, although they are called the same they will have different UUIDs so you will be able to create them. But we do not want to allow equal names in the same slice since it is confusing.

**Comment by msune** [comment]
Well if the problem is really having duplicated VM names in a slice nothing will solve it at the level of the agent, since you can still have 2 VMs within the same slice&project in two different servers.

In fact, if you consider a really fully distributed system (no central AM or GUI) you cannot prevent this anyway.

The fix was to avoid deleting existing .conf files from duplicated names, not to avoid duplicated names.

Please revise the fix&discussion ;)

**Comment by lbergesio** [comment]
Exactly.
That is how it was fixed. Just distinguishing between the possible exceptions during the creation process. If it is due to the fact that a VM in that slice was already present (.conf and.img files in the slice directory) then avoid deleting these file.
