### ISSUE TITLE
 [Errno 113] No route to host after start oxad

### ISSUE THREAD

**Issue by cledsons** [fp7-ofelia/ocf#194]
Hello,

Here in our Fibre testbed  at UFF Island, we getting the following message in  /opt/ofelia/oxa/log/error.log after oxad startup:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/opt/ofelia/oxa/repository/vt_manager/src/python/agent/utils/ServiceThread.py",  line 27, in run     self.__method(self.__param)
  File "/opt/ofelia/oxa/repository/vt_manager/src/python/agent/monitoring/MonitoringDispatcher.py", line 53, in processMonitoring  
   raise e
error: [Errno 113] No route to host

Thanks for any help!

**Comment by alvico** [comment]
Seems that you not have connectivity to the hosts, could you check that your machine with the oxa can reach the xen servers?

try a ping.

**Comment by cledsons** [comment]
Thanks for reply

I have connectivity. oxad is installed on Dom0 and OCF on DomGuest and both
ping each other.

Is there a way to find out, in the settings, the IP address that the message
refers to?

Thank you again.

2014-01-27 alvico notifications@github.com

> Seems that you not have connectivity to the hosts, could you check that
> your machine with the oxa can reach the xen servers?
> 
> try a ping.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/fp7-ofelia/ocf/issues/194#issuecomment-33349914
> .

## 

```
    [ ]'s
```

Cledson Sousa

**Comment by CarolinaFernandez** [comment]
Hi,

I guess you are seeing that message because the variables `VTAM_IP`, `VTAM_PORT`, `XMLRPC_USER`, `XMLRPC_PASS` are not correct. You can find the file in [`/opt/ofelia/oxa/repository/vt_manager/src/python/agent/mySettings.py`](https://github.com/fp7-ofelia/ocf/blob/ofelia.stable/vt_manager/src/python/agent/mySettings-example.py#L21-L24).

This error should indicate that the Agent is not able to communicate back (e.g. the VM status) to the VT AM. You can try the following to check the connectivity to the VTM AM machine. If the `ping` method does not return anything back, either check the (IP, port) or the (user, password):

```
~# python
>>> import xmlrpclib
>>> server = xmlrpclib.Server("https://<XMLRPC_USER>:<XMLRPC_PASS>@<VTAM_IP>:<VTAM_PORT>/xmlrpc/plugin")
>>> server.ping("test")
'test'
```

**Comment by cledsons** [comment]
Thanks ... Solved.
