### ISSUE TITLE
Error during start or deleting VM Agregate on OCF 

### ISSUE THREAD

**Issue by cledsons** [fp7-ofelia/ocf#196]
Hello! Cledson again!

Now, during starting or deleting VMs on OCF web gui 
 /opt/ofelia/oxa/log/error.log shows me 

libvir: Xen error : Domain not found: xenUnifiedDomainLookupByUUID
29/01/2014 02:23:58 PM [Thread-8>XenProvisioningDispatcher.py:83] ERROR: Cannot find VM in CACHE FS project:4fc307a8-e624-410b-987c-e6a560078f6d, slice:27058d10-bbef-400b-9433-24e0090193ed, name:XXXX

Thanks for any help.

**Comment by CarolinaFernandez** [comment]
Hi, Cledson

what you are commenting should be happening because the Xen hypervisor cannot find the VM in that location. I will explain the workflow to help a little with that error, but you should check the logs further and see if the VM was properly created and/or initiated.

How it works:
1. When a VM is created (in your case: XXXX), the physical files (in your case: `XXXX_swap.img`, `XXXX.img`, `XXXX.conf`).are placed (again, in your case) under _/opt/ofelia/oxa/remote/vms/4fc307a8-e624-410b-987c-e6a560078f6d/27058d10-bbef-400b-9433-24e0090193ed_
2. When a VM is started, those files are moved to _/opt/ofelia/oxa/cache/vms/4fc307a8-e624-410b-987c-e6a560078f6d/27058d10-bbef-400b-9433-24e0090193ed_

The last step refers to the error you are pointing to, and suggest that the Xen hypervisor cannot find the file in order to operate with it.

Could you check that your XXXX VM is under the location of step 2 (if VM already started) or 1 (if VM stopped), and check if `xm list` show the machine as running?

Also: for the `libvir: Xen error : Domain not found: xenUnifiedDomainLookupByUUID` message, it's the same that happens [with other modules that use Xen](https://fedorahosted.org/cobbler/wiki/VirtualizationTroubleshooting).

**Comment by cledsons** [comment]
Thanks Again. (solved)

**Comment by alvico** [comment]
Hello, could you explain how did you fixed the problem, so others with similar errors could use your solution?

**Comment by cledsons** [comment]
In my case, somehow,  it was missing the shell environment var $OXA_DIRECTORY. I've just add a line: 

call("export OXA_DIRECTORY=/opt/ofelia/oxa/") in file /opt/ofelia/oxa/bin/OfeliaAgent.py 

The error "libvir: Xen error : Domain not found: xenUnifiedDomainLookupByUUID" remains, but VMs are being create normally now.
