### ISSUE TITLE
Cant delete Broken VMs

### ISSUE THREAD

**Issue by cledsons** [fp7-ofelia/ocf#198]
Hello! Cledson again and again! 

During our tests we create a lot of VMs and most of them are broken. 
On Issue "Deleting VMs via the tests/deleteVM.py script #140 " you mention some scripts: ...expedient/src/python/plugins/vt_plugin/test/deleteVM.py, but you recommend for development phase only.

The issue is: I cant delete broken VMs. Is there  any means to do this?

**Comment by CarolinaFernandez** [comment]
Hi Cledson,

indeed, those scripts should not be necessary as VMs should be seldom broken. However, since this is happening quite often in your case, you may [follow this set of steps](https://github.com/fp7-ofelia/ocf/wiki/Operational-troubleshooting#wiki-stalled-vms-in-expedient-andor-in-vt-am).

Another

**Comment by cledsons** [comment]
Solved.
Many thanks!
