### ISSUE TITLE
Check random error when links between switches are not drawn in the topology

### ISSUE THREAD

**Issue by lbergesio** [fp7-ofelia/ocf#21]
May be a bug, probably related with OpenVswitch.... it happened with mininet and NetFPGAs.

**Comment by CarolinaFernandez** [comment]
Apparently this happens because of the FlowVisor, when it does not obtain the links properly (most of the times in preprod).

This can be tested with the mininets and the 2 environments: the one in the SDK will show links (and the command `fvctl getLinks` in a terminal of the SDK will show the correct number of connections - e.g. 6 links for a linear,4 topology); but the other will show no links at all (and the command `fvctl getLinks` in the terminal of this environment will show no lines either).

**Comment by CarolinaFernandez** [comment]
This may happen because of the FlowVisor version (0.7.2) or because the configuration files passed to it correspond to another version.

**It seems to work consistently now after a couple of FW reboots & AM updates -- although more tests are welcomed**

Version 0.8.1 is used now (folders /usr/sbin/flowvisor, /usr/sbin/fvconfig, /usr/bin/fvctl, /usr/etc/flowvisor); but 0.8.3 seems to work nicely too. _Just make sure not to use 0.8.4 - since its behavior floods every terminal with logged data._
