### ISSUE TITLE
Move LDAP settings to a more configurable location, and stop tracking them in the repository

### ISSUE THREAD

**Issue by lbergesio** [fp7-ofelia/ocf#29]
This is needed for installation out from OFELIA which have specific LDAP set ups. Since the ldap settings files are tracked, if customized, they will be replaced in the next upgrade.

**Comment by CarolinaFernandez** [comment]
Fixed.

File _expedient/src/python/expedient/clearinghouse/localLdapSettings-example_ will be used for any custom settings at non-OFELIA installation. Installation and upgrade to 0.3.1 were consequently updated.

**Comment by msune** [comment]
Sorry in advance, but I have to disagree :)

Original local-settings is meant to encapsulate whatever override of the default settings (including LDAP). Since LDAP is a very specific thing, and by default should be disabled (as for now), I strongly suggest to keep localsettings-example as the unique overriding settings file.

Maybe it could be added to the localsettings-example a couple of commented lines with the LDAP overriding directives, but I still feel is too complex and particular to even put it on the single localsettings-exaple

**Comment by CarolinaFernandez** [comment]
Previous changes to the structure were _rollback'ed_.
Setting files now with a new format and more comments.
