### ISSUE TITLE
Slow rendering of the slice panel when OF AMs are not reachable

### ISSUE THREAD

**Issue by msune** [fp7-ofelia/ocf#41]
THe Slice panel renders very slowly when one or more OF AMs are temporally not reachable. It might be necessary to use available flag in Expedient, to skip synchronous calls.

**Comment by CarolinaFernandez** [comment]
Fixed.

The method that computed the data to show via UI was looking for the granted FlowSpace of OpenFlow AMs it couldn't even reach (that meant circa 23 seconds to load a page with non reachable OF AMs).

Any OF AM should check in the future its availability (e.g. `if agg.available:` and similar) prior to ask for any granted FlowSpace.

**Comment by CarolinaFernandez** [comment]
When an AM first changes its status (unavailable --> available), the first time that the slice detail's page -- for a slice with this AM -- is loaded, it takes approx. 30 seconds. Too much.

This happened before even when the AM was unavailable, because there was some data (I think it was the _granted flowspace_) being calculated for every Openflow aggregate.

Now it happens only the first time, but yet should be solved.

The file to check is `expedient/src/python/expedient/ui/html/views.py`

**Comment by CarolinaFernandez** [comment]
The issue with the first time has been enhanced.

What happened is that even when the topology resources were loaded only when the aggregate was reachable (`aggregate.status = True`); this status was not properly updated within the callbacks that ask for the aggregate status (`/aggregate/status/<agg_id>/`)

The method that is called in the end by the callbacks is inside the file `expedient/src/python/expedient/clearinghouse/aggregate/views.py`

> ```
> def status_img_url(request, agg_id):
>     """Get the url for the status image of the aggregate"""
>     aggregate = get_object_or_404(Aggregate, pk=agg_id)
>     success = HttpResponse(reverse("img_media", args=["active.png"]))
>     fail = HttpResponse(reverse("img_media", args=["inactive.png"]))
>     try:
>         if aggregate.as_leaf_class().check_status():
>             return success
>         else:
>             return fail
>     except:
>         logger.error(traceback.format_exc())
>         return fail
> ```

The method [check_status](https://github.com/fp7-ofelia/ocf/blob/ofelia.stable/expedient/src/python/openflow/plugin/models.py#L238) sees that the aggregate status is set to True (in the models) and that it is really _ping-eable_. When an AM is _back to life_, the aggregate status (in the model) is still set to False, even when the ping is successful; so the return 

This checks the status, but does not update it. Somewhere else shall exist a method that updates the availability status in the `OpenFlowAggregate` object, but **its frequency is of 1 minute**. If the aggregate varies -from available to unavailable- in the same moment the experimenter loads the slice details page, it will take up to 1 minute to load (because the status of the AM is still `True` and therefore tries to retrieve information, even if it is really not reachable).

## 

Therefore, **one solution to this would be to update the status where the callbacks with highest frequency are called** (in the aggregate's view).
That means a final time of 5 seconds (frequency) + ~20 seconds (contact the aggregate and perform whichever operations) to detect some unavailable aggregate in background, instead of the minute needed before.
This reduces the time in which the aggregate status is _non consistent_ and during which this situation may happen.

## 

The new code for the `expedient/src/python/expedient/clearinghouse/aggregate/views.py` file is:

> ```
> def status_img_url(request, agg_id):
>     """Get the url for the status image of the aggregate"""
>     aggregate = get_object_or_404(Aggregate, pk=agg_id)
>     success = HttpResponse(reverse("img_media", args=["active.png"]))
>     fail = HttpResponse(reverse("img_media", args=["inactive.png"]))
>     try:
>         agg_status = aggregate.as_leaf_class().check_status()
>         if agg_status != aggregate.available:
>             aggregate.available = agg_status
>             aggregate.save()
>         if agg_status:
>             return success
>         else:
>             return fail
>     except:
>         logger.error(traceback.format_exc())
>         return fail
> ```
