### ISSUE TITLE
Integration of FOAM in Expedient

### ISSUE THREAD

**Issue by msune** [fp7-ofelia/ocf#59]
Create an Expedient plugin to browse allocate and configure FOAM-like resources using FOAM's XMLRPC.

**Comment by vkotronis** [comment]
I have already formed and implemented an API for legacy compatibility, and now I am trying to resolve the authentication and accessibility issues between FOAM and expedient. Initial tests seem promising. As soon as these issues have been resolved, FOAM can easily be added as the new Expedient OpenFlow Aggregate manager (simple change of URL and credentials).

**Comment by vkotronis** [comment]
Authentication issue solved (use FOAM's credentials without need for certificate exchange), but still the Expedient cannot find the URL endpoint for some very weird reason. We should sit together and deal with the xmlrpc communication once and for all, since I have followed exactly the way of building XMLRPC APIs in FOAM and kept the legacy calls. I see the xmlrpc initial call on my foam.log file but the port is missing for some strange reason. If we debug this, FOAM can easily be added as the new OF AM. More info on the conf-calls.

**Comment by vkotronis** [comment]
This issue now related to #152 and #153. Top priority to issue #152.

**Comment by vkotronis** [comment]
Issue #160 is now the referred one
