### ISSUE TITLE
SSH keys not correctly updated when bootstrapping VMs

### ISSUE THREAD

**Issue by msune** [fp7-ofelia/ocf#6]

**Comment by CarolinaFernandez** [comment]
**Update**: this works OK for VMs whose IP has not yet been assigned to a public certificate in the `known_hosts` file. For _new_ IPs the ssh can be performed without any problem.

When the VM template is generated on the disk, the SSH key of the template ( **or the SSH key of a previous template with the same IP**) is left at the `~/.ssh/known_hosts` file. Then, when a user tries to access via SSH to some VM the known error appears:

> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> @    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
> Someone could be eavesdropping on you right now (man-in-the-middle attack)!
> It is also possible that the RSA host key has just been changed.

**Comment by CarolinaFernandez** [comment]
False alarm. Everything working as expected.

The **general explanation**, for future reference:

When the SSH connection between H (host) and S (server) is established, both of them exchange their public keys.

If this is the first time that H and S get connected, the experimenter E at H will see the following message:

> The authenticity of host '1.2.3.4 (1.2.3.4)' can't be established.
> RSA key fingerprint is f3:cf:58:ae:71:0b:c8:04:6f:34:a3:b2:e4:1e:0c:8b.
> Are you sure you want to continue connecting (yes/no)? 

If the experimenter continues connecting, he/she can later check the `~/.ssh/known_hosts` files, where a new entry will be appended. This entry is the IP of the server and its public key; then on future connections S will be a trusted (known) host for H.

The **specific explanation**:

In the OCF case, the host H1 from which the experimenter E1 connects to another server (e.g. the virtual machine M1) would be their own, so the public key for M1 would be added in `~/.ssh/known_hosts` inside H1, after the first SSH connection. E1 may delete H1 through the Expedient after the experiment has concluded.

Since there is a limited range of IPs, the next experimenter (E2) that were to create a new virtual machine (M2) would receive the 1st available IP -- in this case it could be the one freed by H1. If the public (and therefore also the private) key for the same IP remained the same (as it would happen with a normal host), then E1 could end up accessing M2 ( _my guess: providing that E1 was also added as a user of the slice where E2 created M2 and therefore has the right to access the machine_), because this would share the same certificates as M1.

Therefore, each time a fresh VM is created, the pair of keys are randomly generated. If somebody ssh'ed to a VM and then destroyed it; after that created another (and the latter received the same IP as the one before it), there would exist an entry in `~/.ssh/known_hosts` for that IP, but with different public key.

**This situation would cause the error quoted in the previous post, but it can be easily solved by the experimenter by removing the offending line (marked in that error message) from that file**.
