### ISSUE TITLE
Theme manager not working for ui/ subfolder specializations

### ISSUE THREAD

**Issue by msune** [fp7-ofelia/ocf#84]
Theme manager cannot override files like:

/opt/ofelia/expedient/src/templates/default/expedient/clearinghouse/slice/ui/list_vms.html 

Because the real source (where the template is loaded) is not this path but :

/opt/ofelia/expedient/src/python/expedient/ui/html/templates/html/

This implies moving the templates from that folder to the right /opt/ofelia/expedient/src/templates/default folder

**Comment by CarolinaFernandez** [comment]
Some explanation first, as a record for myself or any other who may find this useful:

### Theme Manager behavior

Inside Django's settings there is a new template directory inside which Django will try to find the templates. The first line -so that it overrides any _default_ template- is the path where the templates for each theme (.e.g default) will be placed; therefore the first place to look.

> TEMPLATE_DIRS = [
>     **os.path.join(SRC_DIR, 'templates/default'),**
>     os.path.join(SRC_DIR, 'templates/default/expedient/clearinghouse'),
>     os.path.join(SRC_DIR, 'templates/default/expedient/common'),
>     os.path.join(SRC_DIR, 'python/vt_plugin/views/templates/default'),
> ]

However, it seems that in the `expedient/src/python/expedient/ui/html/views.py` file there are some "direct_to_template" methods that return the templates in the later path (the one with the real sources) in a way that does not allow this (see method "bookOpenflow" in this view):

> template="html/select_resources.html",

**Might be related to this**

Strange thing about symbolic links here:

`expedient/src/templates/default/expedient/clearinghouse/slice`, has the following symbolic link inside:

ui -> `../../../../../python/expedient/ui/html/templates/html/`

that means `expedient/src/python/expedient/ui/html/templates/html`, which has the following link inside:

html -> `../../../../../python/expedient/ui/html/templates/html/` ( **broken link**)

**Comment by msune** [comment]
UI should use templates/ folder. These symlinks were only meant to use the structure of files all in the templates (for some .py around there) while files were not being moved, and let the rest use old paths. 

yes we should do it asap, as it was a bad patch, but no time at the moment ;)

**Comment by CarolinaFernandez** [comment]
Done.

Templates at `expedient/src/python/expedient/ui/html/templates/html/` were moved to `expedient/src/templates/<theme_name>/expedient/clearinghouse/slice` and everything seems to work correctly.

Therefore, the 1st directory could be deleted and the symlink in the 2nd ("ui") is used no more and could also be deleted.
