### ISSUE TITLE
Exceptions rised from Optin sometimes contain the full URL including HTTP basic auth

### ISSUE THREAD

**Issue by msune** [fp7-ofelia/ocf#85]
Exceptions rised from Optin sometimes contain the full URL including HTTP basic auth

**Comment by CarolinaFernandez** [comment]
If some examples were available here, please... ;)

As for now I guess this happens [_in the optin only, and information is sent to the logs_] because there is some connection error with a `SeverProxy` object that fails when connecting to some method in the remove server: e.g. to the method "listDevices", "getDeviceInfo", etc. There, the exception is controlled, but the whole stack trace is shown in the log.

Files that may show the full URL are:
- `optin_manager/src/python/openflow/optin_manager/admin_manager/views.py` (lines: 186, 316, 665, 766, 940, 994, 1081, 1176, 1250)
- `optin_manager/src/python/openflow/optin_manager/opts/views.py` (lines: 67, 217, 331, 482, 569)
- `optin_manager/src/python/openflow/optin_manager/xmlrpc_server/ch_api.py` (lines: 305, 335, 367, 417)
- `optin_manager/src/python/openflow/optin_manager/xmlrpc_server/models.py` (lines: 18, 33, 41, 69)

**Comment by lbergesio** [comment]
Fixed. Expections are parsed at two points via an improved parseFVexception() method. First time in the optin CH api and secondly in the slice controller (views.py) of Expedient.
